### ISSUE TITLE
Big O/Big Easy

### ISSUE THREAD

**Issue by Slugger** [cardrank/cardrank#2]
Can this be used for ranking Big O/Big Easy?  Or even extending it out to other forms of Omaha 8 or better (i.e. 7 card, 8 card, 9 card Omaha).

**Comment by cardrank** [comment]
I believe "Big O" is where the player has 5 hole cards, correct? I don't know what "Big Easy" is, and I'm unable to find information on Google about it. But yes, there is no reason where the current evaluator could not be adopted for 8, or 9 card evaluation, so long as the final poker hand is based on 5 cards. You'd need to write a "chooser" that basically selects the minimum hand rank evaluation of any 5 of X cards, where X is 8 or 9 cards. The current evaluator works properly for 5, 6, and 7 card hands. If you have reference information for the rules for those other forms of Omaha, I'd be glad to look at them and try to put it into this package.

If you'd like to submit a PR, I'd merge the code if works and is clean.

Note: I would expect a 5 of 9 implementation to be _extremely_ slow, at least in comparison to the current hand evaluation.

**Comment by Slugger** [comment]
Big O => 5 card Omaha hi/low
Big Easy => 6 card Omaha hi/low
7+ card Omaha hi/low => degen games -- but I've been known to play them :)

They all rank/play the same as regular Omaha 8 or better, just the difference is the number of hole cards each player gets.  But all are same as Omaha -- must use exactly two from your hole cards and 3 from the board to make your high and low hands.

What I'm actually interested in is trying to calculate the equities of Big O/Big Easy/etc. hands.  First things first, I need to find something that can rank such hands and I came across this pkg.

**Comment by cardrank** [comment]
I just tagged a new version, `v0.8.0` that has the following poker variants:

```
	Holdem         Type = 'H'<<8 | 'h' // Hh
	Short          Type = 'H'<<8 | 's' // Hs
	Royal          Type = 'H'<<8 | 'r' // Hr
	Double         Type = 'H'<<8 | 'd' // Hd
	Showtime       Type = 'H'<<8 | 't' // Ht
	Swap           Type = 'H'<<8 | 'w' // Hw
	Omaha          Type = 'O'<<8 | '4' // O4
	OmahaHiLo      Type = 'O'<<8 | 'l' // Ol
	OmahaDouble    Type = 'O'<<8 | 'd' // Od
	OmahaFive      Type = 'O'<<8 | '5' // O5
	OmahaSix       Type = 'O'<<8 | '6' // O6
	Courchevel     Type = 'O'<<8 | 'c' // Oc
	CourchevelHiLo Type = 'O'<<8 | 'e' // Oe
	Fusion         Type = 'O'<<8 | 'f' // Of
	Stud           Type = 'S'<<8 | 'h' // Sh
	StudHiLo       Type = 'S'<<8 | 'l' // Sl
	Razz           Type = 'R'<<8 | 'a' // Ra
	Badugi         Type = 'B'<<8 | 'a' // Ba
```

You can also dynamically define your own `Type` now, as nothing is hard coded. Take a look at the new `Dealer` and specifically the `TestDealer` func for how to use the same API for dealing any of these hand types.

The rules for Showtime, Omaha 5, Omaha 6, Courchevel, Courchevel Hi/Lo, and Fusion were cribbed from PokerStars' rules web pages. Please let me know if any of these are incorrect, as I have not extensively tested these. However, they appear to all be working correctly, as I have manually verified/checked the outputs of a few hundred hands.
