### ISSUE TITLE
eval.Desc(false).Unused not returning unused cards 

### ISSUE THREAD

**Issue by kaleab-taye** [cardrank/cardrank#5]
hello i was making a bot that automatically performs an action by analyzing the cards it has, and using the package cardrank i was able to evaluate the rank of the cards but the problem is i couldn't find a way to identify the cards that were used in the ranking process.
i tried using `.Unused` field of the type `*cardrank.Eval` but it is not working as expected

    ev := cardrank.Video.Eval(cardrank.Must(package_cards), community_cards)

    fmt.Printf(" -> %s\n", ev.Desc(false).Best)

    fmt.Printf("0-> %s\n", ev.Desc(false).Unused)

no matter the rank of the cards `ev.Desc(false).Best` always returns all the cards and  `ev.Desc(false).Unused` returns an empty array.

is there any other way i can find the used and unused cards in the ranking process ? of maybe is there something i need to change

**Comment by kaleab-taye** [comment]
it appears `.Unused` returns the cars that wont be useful of the ranking process, (the cards that are more than five)

**Comment by cardrank** [comment]
@kaleab-taye you're using the `Video` type. There are only pocket cards on the video type, and there are no "best" or "unused" cards if the pocket doesn't make at least a pair of Jacks or better:

```sh
$ cat main.go 
package main

import (
	"fmt"

	"github.com/cardrank/cardrank"
)

func main() {
	v := cardrank.Must("Jh Js 5c 3c 4h 8d Kd")
	ev := cardrank.Holdem.Eval(v, nil)
	fmt.Println("cards:", ev.HiBest, ev.HiUnused)
}
$ go run main.go 
cards: [Jh Js Kd 8d 5c] [4h 3c]
```

**Comment by cardrank** [comment]
Sorry, above I accidentally changed `Video` to `Holdem` to ensure what I was writing was correct. If you run the above, with `Video`, you will see that it has the same output.

If you want a simple poker style evaluation, either use the `Holdem` type, which you can pass 5 cards to the pocket or to the board (doesn't really matter, so long as there is 5, 6, or 7 cards to make a best-5 hand out of).

Alternately, you can create your own eval func:
```sh
$ cat main.go 
package main

import (
	"fmt"

	"github.com/cardrank/cardrank"
)

func main() {
	// create eval func (setting normalize to true, to normalize the order of suit presentation)
	f := cardrank.NewCactusEval(true, false)
	// create storage for the eval values
	ev := cardrank.EvalOf(cardrank.Holdem)
	// create the hand to be evaluated
	v := cardrank.Must("Jh Js 5c 3c 4h 8d Kd")
	// eval a pocket, with no community board
	f(ev, v, nil)
	// display result
	fmt.Println("eval:", ev.HiRank, ev.HiBest, ev.HiUnused)
}
$ go run main.go 
eval: Pair [Jh Js Kd 8d 5c] [4h 3c]
```
