### ISSUE TITLE
Marshalling?

### ISSUE THREAD

**Issue by delaneyj** [cardrank/cardrank#6]
How would one Marshal and uninstall the dealer to JSON?

**Comment by cardrank** [comment]
@delaneyj the `Dealer` itself isn't designed to be specifically marshaled. if one needs to reconstitute the state, the best way would be to create a separate type that manages the shuffle seed (or the specific card deck), the game/hand type that played, the players, and the specific run out state (eg, what street is it on). 

this is how we use this in production. 

we have not made public the code for handling the game state, as it's very specific to our backend, but it should be relatively straight forward. after you reload the variables, the way the cards are dealt is easy managed by just calling `Next()` to the appropriate street.

gl
